version: '1'

services:
  nginx: 
    image: nginx:latest
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./app:/var/www
      - ./logc:/var/log/nginx
    links:
      - php
  php: 
    build: ./images/php
    links: 
      - mysql
    volumes:
      - ./app:/var/www
  mysql: 
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}